###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
---
services:
    mysql:
        image: 'mysql:8.0.31'
        working_dir: /application
        restart: unless-stopped
        networks:
          survey: null
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=rootpw
            - MYSQL_DATABASE=survey
            - MYSQL_USER=survey
            - MYSQL_PASSWORD=survey
        ports:
            - '28002:3306'

    webserver:
        image: 'nginx:1.27.2-alpine3.20-slim'
        working_dir: /application
        restart: unless-stopped
        networks:
          survey: null
          traefik_web: null
        volumes:
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - '.:/application'
        ports:
            - '28000:80'
        extra_hosts:
          - 'host.docker.internal:host-gateway'
        labels:
          traefik.docker.network: traefik_web
          traefik.enable: "true"
          traefik.http.middlewares.survey-https-redirect.redirectscheme.scheme: https
          traefik.http.routers.survey.entrypoints: websecure
          traefik.http.routers.survey.middlewares: httpd-security@file
          traefik.http.routers.survey.rule: "Host(`goldstandardchorus.jeffharris.us`)"
          traefik.http.routers.survey.tls.certresolver: lets-encrypt
          traefik.http.routers.survey.tls: "true"
          traefik.port: "80"
        mem_limit: "10M"

    php-fpm:
        restart: unless-stopped
        build: phpdocker/php-fpm
        networks:
          survey: null
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/cli/conf.d/99-overrides.ini'

networks:
  survey:
    driver: bridge
  traefik_web:
    external: true
...
